/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PosTransctionsRouteImport } from './routes/pos.transctions'
import { Route as AdminTransactionRouteImport } from './routes/admin.transaction'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'

const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PosTransctionsRoute = PosTransctionsRouteImport.update({
  id: '/transctions',
  path: '/transctions',
  getParentRoute: () => PosRoute,
} as any)
const AdminTransactionRoute = AdminTransactionRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pos': typeof PosRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/transaction': typeof AdminTransactionRoute
  '/pos/transctions': typeof PosTransctionsRoute
  '/admin/': typeof AdminIndexRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/transaction': typeof AdminTransactionRoute
  '/pos/transctions': typeof PosTransctionsRoute
  '/admin': typeof AdminIndexRoute
  '/pos': typeof PosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pos': typeof PosRouteWithChildren
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/transaction': typeof AdminTransactionRoute
  '/pos/transctions': typeof PosTransctionsRoute
  '/admin/': typeof AdminIndexRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/logout'
    | '/pos'
    | '/admin/inventory'
    | '/admin/sales'
    | '/admin/transaction'
    | '/pos/transctions'
    | '/admin/'
    | '/pos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/login'
    | '/logout'
    | '/admin/inventory'
    | '/admin/sales'
    | '/admin/transaction'
    | '/pos/transctions'
    | '/admin'
    | '/pos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/logout'
    | '/pos'
    | '/admin/inventory'
    | '/admin/sales'
    | '/admin/transaction'
    | '/pos/transctions'
    | '/admin/'
    | '/pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PosRoute: typeof PosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pos/transctions': {
      id: '/pos/transctions'
      path: '/transctions'
      fullPath: '/pos/transctions'
      preLoaderRoute: typeof PosTransctionsRouteImport
      parentRoute: typeof PosRoute
    }
    '/admin/transaction': {
      id: '/admin/transaction'
      path: '/transaction'
      fullPath: '/admin/transaction'
      preLoaderRoute: typeof AdminTransactionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminTransactionRoute: typeof AdminTransactionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminTransactionRoute: AdminTransactionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PosRouteChildren {
  PosTransctionsRoute: typeof PosTransctionsRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosTransctionsRoute: PosTransctionsRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PosRoute: PosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
